### ISSUE TITLE
Ensure add_fitted_samples works on ordinal and multinomial models in brms and rstanarm

### ISSUE THREAD

**Issue by tmastny** [mjskay/tidybayes#85] opened 2017-10-19 20:52 UTC
Hi Matthew, 

Thanks for making this package. I am having trouble using `add_fitted_samples` for an ordinal model fit using brms. 

When calling the function I get the following error:

```
> data_to_predict %>% add_fitted_samples(mod.male.contact)
Error in t.default(f_fitted_predicted(model, newdata = ., ...)) : 
  argument is not a matrix
```

Below is the 'minimum' code to reproduce this error. Unfortunately the model takes about 5 minutes to fit.

I have also included working code using `fitted(...)` and `posterior_linpred(...)` on the brms model. Based on what I understand from the documentation, `add_fitted_samples` actually calls these functions so it might be helpful.

> add_fitted_samples adds samples from the posterior linear predictor (or the "link") to the data. It corresponds to posterior_linpred in rstanarm or fitted.brmsfit in brms.

Also, `add_predicted_samples` works as well.

I'm not sure if this is a bug or user error. I would appreciate any help or advice. 

Thanks,

Tim
 
```
library(tidyverse)
library(brms)
library(modelr)

library(rethinking)
data(Trolley)
d <- Trolley

# takes a few minutes to fit
mod.male.contact <- brm(response ~ male*contact, data=d,
                        family=cumulative("logit"), threshold="flexible",
                        prior=set_prior("normal(0,10)", class='b'))


data_to_predict <- d %>% data_grid(male = c(0,1), contact = c(0,1)) %>% 
  as.data.frame()

# this fails
data_to_predict %>% add_fitted_samples(mod.male.contact)

# but both these work
fitted(mod.male.contact, data_to_predict)
posterior_linpred(mod.male.contact, newdata=data_to_predict, 
                  scale=linear) %>% as.tibble()

# this also works 
data_to_predict %>% add_predicted_samples(mod.male.contact)
```

**Comment by mjskay** [comment] 2017-10-19 21:17
Hi Tim,

Thanks for this! Yeah, that is a bug on my end. Basically looks like the problem is that with an ordinal model, fitted() returns a 3 dimensional array (d draws * n observations * k outcome categories) instead of a 2 dimensional array (d * n) as most other model types do; in your case there are k = 7 predictions per input row (one for the probability the outcome is in each category). I expect multinomial regression will have a similar issue.

Let me set up some test cases for this and come up with a solution. Likely I will have it generate a data frame with d * n * k rows instead of the usual d * n rows, and add an extra column to contain the category name.

**Comment by mjskay** [comment] 2017-10-20 04:08
I think this should be fixed now. `fitted_samples` should now add a `"category"` column for models where this is necessary. You can rename it using the `category` argument to `fitted_samples`.

So you get something like this (N.B. your row counts will probably be different; I fit the model with a small number of samples to save myself time):

```r
data_to_predict %>% 
  add_fitted_samples(mod.male.contact)
```

```
# A tibble: 7,000 x 7
# Groups:   male, contact, .row, category [28]
    male contact  .row .chain .iteration category  estimate
   <dbl>   <dbl> <dbl>  <dbl>      <dbl>   <fctr>     <dbl>
 1     0       0     1     NA          1 P(Y = 1) 0.1391060
 2     0       0     1     NA          2 P(Y = 1) 0.1498686
 3     0       0     1     NA          3 P(Y = 1) 0.1564165
 4     0       0     1     NA          4 P(Y = 1) 0.1423177
 5     0       0     1     NA          5 P(Y = 1) 0.1479752
 6     0       0     1     NA          6 P(Y = 1) 0.1474441
 7     0       0     1     NA          7 P(Y = 1) 0.1456729
 8     0       0     1     NA          8 P(Y = 1) 0.1489901
 9     0       0     1     NA          9 P(Y = 1) 0.1524746
10     0       0     1     NA         10 P(Y = 1) 0.1384682
# ... with 6,990 more rows
```

And if you prefer having the estimate for each category be its own column, you can use `spread` from the `tidyr` package to transform the above format into what you might need:

```r
data_to_predict %>% 
  add_fitted_samples(mod.male.contact) %>%
  spread(category, estimate)
```

```
# A tibble: 1,000 x 12
# Groups:   male, contact, .row [4]
    male contact  .row .chain .iteration `P(Y = 1)` `P(Y = 2)` `P(Y = 3)` `P(Y = 4)` `P(Y = 5)`
 * <dbl>   <dbl> <dbl>  <dbl>      <dbl>      <dbl>      <dbl>      <dbl>      <dbl>      <dbl>
 1     0       0     1     NA          1  0.1391060 0.10140021  0.1142158  0.2472689  0.1480391
 2     0       0     1     NA          2  0.1498686 0.10130795  0.1230084  0.2398033  0.1380039
 3     0       0     1     NA          3  0.1564165 0.10605638  0.1182229  0.2417242  0.1371223
 4     0       0     1     NA          4  0.1423177 0.10383344  0.1229234  0.2508566  0.1411004
 5     0       0     1     NA          5  0.1479752 0.09873011  0.1226626  0.2455370  0.1415337
 6     0       0     1     NA          6  0.1474441 0.10430693  0.1126454  0.2449970  0.1416509
 7     0       0     1     NA          7  0.1456729 0.10200421  0.1201586  0.2471962  0.1424708
 8     0       0     1     NA          8  0.1489901 0.10409099  0.1195284  0.2496188  0.1380276
 9     0       0     1     NA          9  0.1524746 0.11039025  0.1143617  0.2468368  0.1336678
10     0       0     1     NA         10  0.1384682 0.09687289  0.1236973  0.2478566  0.1487685
# ... with 990 more rows, and 2 more variables: `P(Y = 6)` <dbl>, `P(Y = 7)` <dbl>
```

Let me know if that works.

**Comment by tmastny** [comment] 2017-10-20 15:37
Thanks for the very quick response! 

So I tested out 
`data_to_predict %>% add_fitted_samples(mod.male.contact)`
and it seems to work exactly as you described. 

However, now I am having trouble using`scale='linear'`. 

```
# this breaks
data_to_predict %>% add_fitted_samples(mod.male.contact, scale='linear')
```
I get this error:
```
Error in factor(df[, d + 1], labels = levels[[idim[d]]]) : 
  invalid 'labels'; length 7 should be 1 or 6
```
I think the problem comes from the difference between fitted values on the outcome scale (probabilities of response 1, 2, ...., 7) and on the linear scale (cumulative log odds up to P(Y <=6)). The cumulative logit transform used in the ordinal model by only fits cumulative probability up to P(Y<=6) since we can assume P(Y<=7) is 1.  So when we get predictions on the linear scale we only have 6 outcomes instead of 7. 

You'll see this when you run the code below. 

```
library(tidyverse)
library(brms)
library(modelr)
library(tidybayes)

library(rethinking)
data(Trolley)
d <- Trolley


rstan_options (auto_write=TRUE)
options (mc.cores=parallel::detectCores ()) # Run on multiple cores

# takes a few minutes to fit
mod.male.contact <- brm(response ~ male*contact, data=d,
                        family=cumulative("logit"), threshold="flexible",
                        prior=set_prior("normal(0,10)", class='b'),
                        warmup = 1000, iter = 2000, chains = 2)


data_to_predict <- d %>% data_grid(male = c(0,1), contact = c(0,1)) %>% 
  as.data.frame()

# this works now
data_to_predict %>% add_fitted_samples(mod.male.contact)

# this breaks
data_to_predict %>% add_fitted_samples(mod.male.contact, scale='linear')

# Error in factor(df[, d + 1], labels = levels[[idim[d]]]) : 
#  invalid 'labels'; length 7 should be 1 or 6

# but this works
fitted(mod.male.contact, data_to_predict, scale='linear')

# however we get only 6 outcomes instead of the 7 when scale='response'

```

**Comment by mjskay** [comment] 2017-10-20 15:50
Hah, yup. Literally a 5-character fix, I forgot to pass through the remaining args when determining levels for the output categories.

**Closed** 2017-10-20 15:55 UTC
